name: CI

on:
  push:
    branches:
      - main
      - 'feat/*'
      - 'fix/*'
  pull_request:
    branches:
      - main
      - 'feat/*'
      - 'fix/*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run lint
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Cypress Run
      - uses: cypress-io/github-action@v2
      - with:
          build: npm run build
          start: npm start
